# -*- coding: utf-8 -*-
"""tpotUnix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M0BDLzyK09RWeCSOBrrYuiV3dEL3nFuD
"""

import pandas as pd
import argparse
from pathlib import Path
from data_utils import load_dataset, underSample2Min
from tpot import TPOTClassifier
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import classification_report, accuracy_score

parser = argparse.ArgumentParser()
parser.add_argument("--data", default="data/dati_Pico.xlsx")
parser.add_argument("--seed", type=int, default=42)
args = parser.parse_args()

df = load_dataset(args.data)
df = underSample2Min(df, "Category", random_state=args.seed)
X, y = df["Text"], df["Category"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=args.seed, stratify=y)


cv4 = CountVectorizer(
     ngram_range = (1,3),
     min_df = 2,
     stop_words = 'english'
)
xTrainDtm = cv4.fit_transform(X_train)
xTestDtm = cv4.transform(X_test)


tpot = TPOTClassifier(
    generations=50,
    population_size=30,
    verbosity=2,
    scoring='f1',
    cv=5,
    n_jobs=-1,
    config_dict='TPOT sparse',
    random_state=args.seed
)


tpot.fit(xTrainDtm, y_train)
y_pred = tpot.predict(xTestDtm)
print(classification_report(y_test, y_pred))

Path("results").mkdir(exist_ok=True)
tpot.export("results/tpot_optimal_pipeline.py")
